# .hidden
---

- include: vars

- vars:
    who: <redacted>

# EXPECTED OUTPUT ----------------------------------------------------------------

# COMMAND: hello *****************************************************************
# hello, <redacted>.

# --------------------------------------------------------------------------------
